// TwinOutputRenderer.jsx
import { useState } from 'react';
import {
  RadarChart, PolarGrid, PolarAngleAxis, PolarRadiusAxis,
  Radar, ResponsiveContainer, BarChart, Bar, XAxis, YAxis, Tooltip, Cell
} from 'recharts';

// ─── Helpers ───
const DownloadBtn = ({ data, filename }) => {
  const download = () => {
    const md = `# ${filename.replace(/_/g, ' ').toUpperCase()}\n\nGenerated by Career Twin\n\n`;
    const body = JSON.stringify(data, null, 2);
    const blob = new Blob([md + '```json\n' + body + '\n```'], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${filename}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };
  return (
    <button onClick={download} className="px-3 py-1.5 bg-gray-100 hover:bg-gray-200 text-gray-700 rounded-lg text-xs font-semibold transition">
      ⬇️ Download Markdown
    </button>
  );
};

const CopyBtn = ({ text, label = '📋 Copy' }) => {
  const [ok, setOk] = useState(false);
  const copy = () => {
    navigator.clipboard.writeText(text);
    setOk(true);
    setTimeout(() => setOk(false), 2000);
  };
  return (
    <button onClick={copy} className="px-3 py-1.5 bg-indigo-50 hover:bg-indigo-100 text-indigo-700 rounded-lg text-xs font-semibold transition">
      {ok ? '✅ Copied!' : label}
    </button>
  );
};

// ─── 1. LinkedIn Renderer ───
const LinkedInRenderer = ({ data }) => {
  const c = data.content;
  const fullText = `${c.hook}\n\n${c.body}\n\n${c.cta}\n\n${c.hashtags?.join(' ')}`;
  return (
    <div className="space-y-4 animate-in fade-in slide-in-from-bottom-4 duration-500">
      <div className="bg-white rounded-xl border border-gray-200 shadow-sm overflow-hidden">
        {/* LinkedIn Header */}
        <div className="p-4 flex items-center gap-3">
          <div className="w-12 h-12 rounded-full bg-gradient-to-br from-indigo-500 to-purple-600 flex items-center justify-center text-white text-lg font-bold">
            {data.meta?.name?.[0] || 'Y'}
          </div>
          <div>
            <div className="font-bold text-gray-900 text-sm">You</div>
            <div className="text-xs text-gray-500">{data.meta?.tone || 'Professional'} • 1h • 🌐</div>
          </div>
        </div>
        {/* Body */}
        <div className="px-4 pb-3 text-sm text-gray-800 whitespace-pre-line leading-relaxed">
          <p className="font-semibold text-gray-900 mb-2">{c.hook}</p>
          <p className="mb-3">{c.body}</p>
          <p className="text-gray-600 italic mb-2">{c.cta}</p>
        </div>
        {/* Hashtags */}
        <div className="px-4 pb-3 flex flex-wrap gap-2">
          {c.hashtags?.map((tag, i) => (
            <span key={i} className="text-xs text-blue-700 font-medium hover:underline cursor-pointer">{tag}</span>
          ))}
        </div>
        {/* Meta bar */}
        <div className="px-4 py-2.5 bg-gray-50 border-t border-gray-100 flex items-center justify-between text-xs">
          <span className="text-gray-600">Engagement: <span className={`font-bold ${c.estimatedEngagement === 'high' ? 'text-emerald-600' : 'text-indigo-600'}`}>{c.estimatedEngagement}</span></span>
          <span className="text-gray-600">Best time: <span className="font-semibold text-gray-900">{c.bestTimeToPost}</span></span>
        </div>
        {/* Fake action bar */}
        <div className="px-4 py-2 border-t border-gray-100 flex gap-6 text-xs font-bold text-gray-500">
          <span className="hover:text-indigo-600 cursor-pointer">👍 Like</span>
          <span className="hover:text-indigo-600 cursor-pointer">💬 Comment</span>
          <span className="hover:text-indigo-600 cursor-pointer">🔄 Repost</span>
        </div>
      </div>

      {/* Suggestions */}
      <div className="bg-indigo-50 rounded-lg p-4 border border-indigo-100">
        <h5 className="text-xs font-bold text-indigo-900 uppercase mb-2">💡 Twin Intelligence</h5>
        <div className="text-xs text-indigo-800 space-y-1">
          <p>• Media: <span className="font-medium">{c.mediaSuggestion}</span></p>
          <p>• Posts with architecture diagrams get <span className="font-medium">3.2x more engagement</span> for tech roles.</p>
          <p>• Comment on 3 posts before publishing to warm up the algorithm.</p>
        </div>
      </div>

      <div className="flex gap-2">
        <CopyBtn text={fullText} label="📋 Copy Post" />
        <DownloadBtn data={data} filename="linkedin_post" />
      </div>
    </div>
  );
};

// ─── 2. Portfolio Renderer ───
const PortfolioRenderer = ({ data }) => {
  const c = data.content;
  const arch = c.architecture || {};
  return (
    <div className="space-y-5 animate-in fade-in slide-in-from-bottom-4 duration-500">
      {/* Header */}
      <div className="flex items-start justify-between">
        <div>
          <h3 className="text-lg font-black text-gray-900">{c.title}</h3>
          <div className="flex gap-2 mt-2">
            <span className={`px-2 py-0.5 rounded text-[10px] font-bold uppercase ${c.complexity === 'advanced' ? 'bg-rose-100 text-rose-700' : c.complexity === 'intermediate' ? 'bg-amber-100 text-amber-700' : 'bg-emerald-100 text-emerald-700'}`}>
              {c.complexity}
            </span>
            <span className="px-2 py-0.5 rounded text-[10px] font-bold uppercase bg-gray-100 text-gray-700">
              {c.estimatedHours} hrs
            </span>
          </div>
        </div>
      </div>

      <p className="text-sm text-gray-700 leading-relaxed">{c.brief}</p>

      {/* Architecture Diagram */}
      <div className="bg-gray-50 rounded-xl p-5 border border-gray-200">
        <h4 className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-4">System Architecture</h4>
        <div className="flex flex-col gap-3 max-w-lg mx-auto">
          <div className="bg-blue-50 border-2 border-blue-200 rounded-lg p-3 text-center">
            <div className="text-xs font-bold text-blue-800">{arch.components?.[0] || 'Frontend'}</div>
            <div className="text-[10px] text-blue-600 mt-1">{arch.components?.[1] || 'React + Vite'}</div>
          </div>
          <div className="flex justify-center"><span className="text-gray-400 text-lg">↓</span></div>
          <div className="bg-green-50 border-2 border-green-200 rounded-lg p-3 text-center">
            <div className="text-xs font-bold text-green-800">{arch.components?.[2] || 'API Gateway'}</div>
            <div className="text-[10px] text-green-600 mt-1">{arch.components?.[3] || 'Node.js / Express'}</div>
          </div>
          <div className="flex justify-center gap-12">
            <span className="text-gray-400 text-lg">↙</span>
            <span className="text-gray-400 text-lg">↘</span>
          </div>
          <div className="grid grid-cols-2 gap-3">
            <div className="bg-purple-50 border-2 border-purple-200 rounded-lg p-3 text-center">
              <div className="text-xs font-bold text-purple-800">{arch.components?.[4] || 'AI Service'}</div>
              <div className="text-[10px] text-purple-600 mt-1">Python / FastAPI</div>
            </div>
            <div className="bg-gray-100 border-2 border-gray-300 rounded-lg p-3 text-center">
              <div className="text-xs font-bold text-gray-800">{arch.components?.[5] || 'Database'}</div>
              <div className="text-[10px] text-gray-600 mt-1">PostgreSQL + Redis</div>
            </div>
          </div>
        </div>
        <p className="text-[11px] text-gray-500 mt-4 text-center">{arch.dataFlow}</p>
      </div>

      {/* Deliverables & Metrics */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div className="bg-white rounded-xl border border-gray-200 p-4">
          <h4 className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-3">Deliverables</h4>
          <ul className="space-y-2">
            {c.deliverables?.map((d, i) => (
              <li key={i} className="flex items-start gap-2 text-xs text-gray-700">
                <span className="mt-0.5 text-emerald-500">☑️</span>
                {d}
              </li>
            ))}
          </ul>
        </div>
        <div className="bg-white rounded-xl border border-gray-200 p-4">
          <h4 className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-3">Success Metrics</h4>
          <ul className="space-y-2">
            {c.successMetrics?.map((m, i) => (
              <li key={i} className="flex items-start gap-2 text-xs text-gray-700">
                <span className="mt-0.5 text-indigo-500">📊</span>
                {m}
              </li>
            ))}
          </ul>
        </div>
      </div>

      {/* Repo Structure */}
      <div className="bg-gray-900 rounded-xl p-4 text-gray-300 font-mono text-xs">
        <div className="flex items-center justify-between mb-2">
          <span className="text-gray-500 font-sans font-bold text-[10px] uppercase">Repo Structure</span>
          <span className="text-gray-600">📁 {c.title?.toLowerCase().replace(/\s+/g, '-') || 'project'}</span>
        </div>
        <div className="space-y-1">
          {c.githubRepoStructure?.map((f, i) => (
            <div key={i} className={`pl-${f.startsWith('/') ? '2' : '4'} text-gray-400`}>
              {f.endsWith('.md') || f.endsWith('.yml') ? '📄' : '📁'} <span className={f.endsWith('.md') ? 'text-blue-300' : 'text-gray-300'}>{f}</span>
            </div>
          ))}
        </div>
      </div>

      <div className="flex gap-2">
        <CopyBtn text={c.learningOutcomes?.join('\n') || c.brief} label="📋 Copy Brief" />
        <DownloadBtn data={data} filename="portfolio_brief" />
      </div>
    </div>
  );
};

// ─── 3. Interview Renderer ───
const InterviewRenderer = ({ data }) => {
  const c = data.content;
  const [openQ, setOpenQ] = useState(0);
  const radarData = Object.entries(c.scoringMatrix || {}).map(([k, v]) => ({
    subject: k.replace(/([A-Z])/g, ' $1').replace(/^./, s => s.toUpperCase()),
    A: v,
    fullMark: 40
  }));

  const diffColor = c.difficulty === 'hard' || c.difficulty === 'google_faang' ? 'text-rose-600 bg-rose-50' : 'text-amber-600 bg-amber-50';

  return (
    <div className="space-y-5 animate-in fade-in slide-in-from-bottom-4 duration-500">
      <div className="flex items-center justify-between">
        <div>
          <h3 className="text-lg font-black text-gray-900">{c.role} — Mock Interview</h3>
          <div className="flex gap-2 mt-2">
            <span className={`px-2 py-0.5 rounded text-[10px] font-bold uppercase ${diffColor}`}>{c.difficulty}</span>
            <span className="px-2 py-0.5 rounded text-[10px] font-bold uppercase bg-gray-100 text-gray-700">⏱ {c.timeLimit}</span>
          </div>
        </div>
      </div>

      {/* Scoring Matrix Radar */}
      <div className="bg-white rounded-xl border border-gray-200 p-4">
        <h4 className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-2">Scoring Matrix</h4>
        <div className="h-64 w-full">
          <ResponsiveContainer>
            <RadarChart data={radarData}>
              <PolarGrid stroke="#e5e7eb" />
              <PolarAngleAxis dataKey="subject" tick={{ fontSize: 11, fill: '#4b5563' }} />
              <PolarRadiusAxis angle={30} domain={[0, 40]} tick={{ fontSize: 10, fill: '#9ca3af' }} />
              <Radar name="Weight" dataKey="A" stroke="#4f46e5" fill="#4f46e5" fillOpacity={0.25} />
            </RadarChart>
          </ResponsiveContainer>
        </div>
      </div>

      {/* Questions Accordion */}
      <div className="space-y-3">
        <h4 className="text-xs font-bold text-gray-500 uppercase tracking-wider">Questions ({c.questions?.length})</h4>
        {c.questions?.map((q, i) => (
          <div key={i} className="bg-white rounded-xl border border-gray-200 overflow-hidden">
            <button
              onClick={() => setOpenQ(openQ === i ? -1 : i)}
              className="w-full px-4 py-3 flex items-center justify-between text-left hover:bg-gray-50 transition"
            >
              <div className="flex items-center gap-3">
                <span className={`px-2 py-0.5 rounded text-[10px] font-bold uppercase ${q.type === 'system_design' ? 'bg-purple-100 text-purple-700' : q.type === 'behavioral' ? 'bg-blue-100 text-blue-700' : 'bg-amber-100 text-amber-700'}`}>
                  {q.type}
                </span>
                <span className="text-sm font-semibold text-gray-800 line-clamp-1">Q{i + 1}: {q.question.substring(0, 60)}...</span>
              </div>
              <span className="text-gray-400 text-xs">{openQ === i ? '▲' : '▼'}</span>
            </button>
            {openQ === i && (
              <div className="px-4 pb-4 space-y-3 border-t border-gray-100">
                <p className="text-sm text-gray-800 mt-3 font-medium">{q.question}</p>
                <div className="bg-indigo-50 rounded-lg p-3 border border-indigo-100">
                  <p className="text-[11px] font-bold text-indigo-900 uppercase mb-1">Rubric</p>
                  <p className="text-xs text-indigo-800">{q.rubric}</p>
                </div>
                <div className="bg-amber-50 rounded-lg p-3 border border-amber-100">
                  <p className="text-[11px] font-bold text-amber-900 uppercase mb-1">Follow-up</p>
                  <p className="text-xs text-amber-800">{q.followUp}</p>
                </div>
                {q.sampleAnswerOutline && (
                  <div className="bg-gray-50 rounded-lg p-3 border border-gray-200">
                    <p className="text-[11px] font-bold text-gray-700 uppercase mb-1">Sample Answer Outline</p>
                    <ol className="list-decimal list-inside text-xs text-gray-700 space-y-1">
                      {q.sampleAnswerOutline.map((pt, idx) => <li key={idx}>{pt}</li>)}
                    </ol>
                  </div>
                )}
                <div className="flex justify-between text-[10px] text-gray-500 font-medium">
                  <span>Difficulty: {q.difficultyScore}/10</span>
                  <span>Time: {q.estimatedTime}</span>
                </div>
              </div>
            )}
          </div>
        ))}
      </div>

      {/* Checklist & Pitfalls */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div className="bg-white rounded-xl border border-gray-200 p-4">
          <h4 className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-3">Prep Checklist</h4>
          <ul className="space-y-2">
            {c.preparationChecklist?.map((item, i) => (
              <li key={i} className="flex items-start gap-2 text-xs text-gray-700">
                <span className="mt-0.5 text-emerald-500">☑️</span>
                {item}
              </li>
            ))}
          </ul>
        </div>
        <div className="bg-white rounded-xl border border-gray-200 p-4">
          <h4 className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-3">Common Pitfalls</h4>
          <ul className="space-y-2">
            {c.commonPitfalls?.map((item, i) => (
              <li key={i} className="flex items-start gap-2 text-xs text-gray-700">
                <span className="mt-0.5 text-rose-500">⚠️</span>
                {item}
              </li>
            ))}
          </ul>
        </div>
      </div>

      <div className="flex gap-2">
        <CopyBtn text={c.questions?.map(q => `Q: ${q.question}\nRubric: ${q.rubric}\n`).join('\n---\n')} label="📋 Copy All Questions" />
        <DownloadBtn data={data} filename="interview_sim" />
      </div>
    </div>
  );
};

// ─── 4. Immunization Renderer ───
const ImmunizationRenderer = ({ data }) => {
  const c = data.content;
  const risk = c.automationRiskScore || 50;
  const riskColor = risk > 70 ? '#ef4444' : risk > 40 ? '#f59e0b' : '#10b981';

  return (
    <div className="space-y-5 animate-in fade-in slide-in-from-bottom-4 duration-500">
      <div className="flex items-center justify-between">
        <h3 className="text-lg font-black text-gray-900">Skill Immunization Plan</h3>
        <span className="px-2 py-0.5 rounded text-[10px] font-bold uppercase bg-indigo-100 text-indigo-700">
          {c.targetLevel}
        </span>
      </div>

      {/* Risk Thermometer */}
      <div className="bg-white rounded-xl border border-gray-200 p-5 flex items-center gap-6">
        <div className="relative w-28 h-28 flex-shrink-0">
          <svg className="w-full h-full transform -rotate-90">
            <circle cx="56" cy="56" r="48" stroke="#e5e7eb" strokeWidth="10" fill="none" />
            <circle cx="56" cy="56" r="48" stroke={riskColor} strokeWidth="10" fill="none"
              strokeDasharray={`${risk * 3.02} 301.59`} strokeLinecap="round" className="transition-all duration-1000" />
          </svg>
          <div className="absolute inset-0 flex flex-col items-center justify-center">
            <span className="text-2xl font-black" style={{ color: riskColor }}>{risk}%</span>
            <span className="text-[10px] text-gray-500 font-bold uppercase">Risk</span>
          </div>
        </div>
        <div className="flex-1">
          <h4 className="text-sm font-bold text-gray-900 mb-1">Automation Risk for {c.vulnerableSkill}</h4>
          <p className="text-xs text-gray-600 mb-2">
            {risk > 70 ? 'High risk. You need to move into architecture and judgment layers immediately.' :
             risk > 40 ? 'Moderate risk. Start cross-training with adjacent strategic skills.' :
             'Lower risk, but continuous elevation is required.'}
          </p>
          <div className="text-xs font-semibold text-indigo-700 bg-indigo-50 inline-block px-2 py-1 rounded">
            Salary Impact: {c.salaryImpactProjection}
          </div>
        </div>
      </div>

      {/* Timeline */}
      <div className="bg-white rounded-xl border border-gray-200 p-5">
        <h4 className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-4">30-Day Timeline</h4>
        <div className="relative border-l-2 border-indigo-200 ml-3 space-y-6">
          {c.phases?.map((phase, i) => (
            <div key={i} className="ml-6 relative">
              <span className="absolute -left-[31px] top-0 w-6 h-6 rounded-full bg-indigo-600 text-white text-[10px] flex items-center justify-center font-bold border-2 border-white shadow-sm">
                W{phase.week}
              </span>
              <h5 className="text-sm font-bold text-gray-900">{phase.focus}</h5>
              <ul className="mt-2 space-y-1.5">
                {phase.tasks?.map((t, j) => (
                  <li key={j} className="text-xs text-gray-600 flex items-start gap-2">
                    <span className="text-indigo-500 mt-0.5">▸</span>
                    {t}
                  </li>
                ))}
              </ul>
              {phase.resources?.length > 0 && (
                <div className="mt-2 bg-gray-50 rounded-lg p-2.5 border border-gray-100">
                  <p className="text-[10px] font-bold text-gray-500 uppercase mb-1">Resources</p>
                  <div className="space-y-1">
                    {phase.resources.map((r, k) => (
                      <p key={k} className="text-[11px] text-gray-700 flex items-center gap-1.5">
                        <span>📚</span> {r}
                      </p>
                    ))}
                  </div>
                </div>
              )}
              {phase.deliverable && (
                <div className="mt-2 text-[11px] font-semibold text-emerald-700 bg-emerald-50 px-2 py-1 rounded inline-block">
                  🎯 Deliverable: {phase.deliverable}
                </div>
              )}
            </div>
          ))}
        </div>
      </div>

      {/* Exit Criteria */}
      <div className="bg-gray-900 rounded-xl p-4 text-gray-300">
        <p className="text-[10px] font-bold text-gray-500 uppercase mb-1">Exit Criteria</p>
        <p className="text-sm text-white font-medium">{c.exitCriteria}</p>
      </div>

      <div className="flex gap-2">
        <CopyBtn text={c.phases?.map(p => `Week ${p.week}: ${p.focus}\n${p.tasks.join('\n')}`).join('\n\n')} label="📋 Copy Plan" />
        <DownloadBtn data={data} filename="immunization_plan" />
      </div>
    </div>
  );
};

// ─── Error Renderer ───
const ErrorRenderer = ({ data }) => (
  <div className="bg-rose-50 border border-rose-200 rounded-xl p-5 text-center">
    <p className="text-2xl mb-2">⚠️</p>
    <h4 className="text-sm font-bold text-rose-900 mb-1">Career Twin Encountered an Issue</h4>
    <p className="text-xs text-rose-700 mb-3">{data.text || data.summary || 'Unknown error'}</p>
    <p className="text-[11px] text-rose-600 bg-white/60 rounded p-2">
      Fallback mode activated. The output above is generated from your profile without AI — it's still actionable.
    </p>
  </div>
);

// ─── Main Router ───
const TwinOutputRenderer = ({ result }) => {
  if (!result) return null;

  if (result.type === 'error') {
    return <ErrorRenderer data={result} />;
  }

  const action = result.actions?.[0];
  if (!action) {
    return (
      <div className="bg-gray-50 rounded-xl p-6 text-center text-sm text-gray-500">
        No actionable output found. Try a more specific command.
      </div>
    );
  }

  switch (action.tool) {
    case 'linkedin_post':
      return <LinkedInRenderer data={action} />;
    case 'portfolio_brief':
      return <PortfolioRenderer data={action} />;
    case 'interview_sim':
      return <InterviewRenderer data={action} />;
    case 'immunization_plan':
      return <ImmunizationRenderer data={action} />;
    default:
      return (
        <div className="bg-white rounded-xl border border-gray-200 p-5">
          <h4 className="font-bold text-gray-900 mb-2">General Output</h4>
          <p className="text-sm text-gray-700 whitespace-pre-line">{result.summary}</p>
          <div className="mt-4">
            <DownloadBtn data={result} filename="career_twin_output" />
          </div>
        </div>
      );
  }
};

export default TwinOutputRenderer;